#pragma once

#if defined(__WXMSW__)
	#ifdef WXMAKINGDLL_NONGUIPLUGIN
		#define WXDLLIMPEXP_NONGUIPLUGIN WXEXPORT
		#define WXDLLIMPEXP_DATA_NONGUIPLUGIN(type) WXEXPORT type
	#if defined(HAVE_VISIBILITY)
		#define WXDLLIMPEXP_INLINE_NONGUIPLUGIN WXEXPORT
	#else
		#define WXDLLIMPEXP_INLINE_NONGUIPLUGIN
	#endif
#elif defined(WXUSINGDLL_NONGUIPLUGIN)
		#define WXDLLIMPEXP_NONGUIPLUGIN WXIMPORT
		#define WXDLLIMPEXP_DATA_NONGUIPLUGIN(type) WXIMPORT type
	#if defined(HAVE_VISIBILITY)
		#define WXDLLIMPEXP_INLINE_NONGUIPLUGIN WXIMPORT
	#else
		#define WXDLLIMPEXP_INLINE_NONGUIPLUGIN
	#endif
	#else
		#define WXDLLIMPEXP_NONGUIPLUGIN
		#define WXDLLIMPEXP_DATA_NONGUIPLUGIN(type) type
		#define WXDLLIMPEXP_INLINE_NONGUIPLUGIN
	#endif
#endif
/*
#if defined(__WXMSW__)
#ifdef WXMAKINGDLL_NONGUIPLUGIN
#define WXDLLIMPEXP_NONGUIPLUGIN __declspec(dllexport)
#elif defined(WXUSINGDLL_NONGUIPLUGIN)
#define WXDLLIMPEXP_NONGUIPLUGIN __declspec(dllimport)
#endif
#else
#define WXDLLIMPEXP_NONGUIPLUGIN
#endif
*/

